services:
  petapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petapi
    ports:
      - "8080:8080"
    volumes:
      - ./pets.mv.db:/app/pets.mv.db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/pets
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_USERNAME=app
      - SPRING_DATASOURCE_PASSWORD=petapi
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
    restart: unless-stopped

